### ISSUE TITLE
Too few arguments to function B13\Container\Backend\Grid\ContainerGridColumn::__construct()

### ISSUE THREAD

**Issue by max951** [t3solution/t3sbootstrap#246]
After updating the extension container from 1.6.1 to 2.0.0 the following error occurs:
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: 
Too few arguments to function B13\Container\Backend\Grid\ContainerGridColumn::__construct(), 3 passed in /html/typo3/typo3_src-11.5.13/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3205 and at least 4 expected | 
ArgumentCountError thrown in file /html/typo3/typo3conf/ext/container/Classes/Backend/Grid/ContainerGridColumn.php in line 29. 

```

I have first helped myself by changing line 334 in Classes/Backend/Preview/T3sbPreviewRenderer.php as follows:
```
-   $columnObject = GeneralUtility::makeInstance(ContainerGridColumn::class, $context, $col, $container);
+   $columnObject = GeneralUtility::makeInstance(ContainerGridColumn::class, $context, $col, $container, false);
```

**Comment by kunoFM** [comment]
Dependencies of t3sbootstrap are "container up to 1.9.9".
So I think since 2.x.y there must be a new compatible version of t3sbootstrap first.

After installing container 2.0.x you can no longer update t3sbootstrap since the dependencies are not met yet.

**Comment by ProWebs** [comment]
I had the same issue solved it by downgrading "container" below 2.0
