### ISSUE TITLE
Issue with creating and displaying containers in BE: PHP 8 +  T3SB 5.2.3

### ISSUE THREAD

**Issue by joergwiedemann** [t3solution/t3sbootstrap#265]
Creating a container (eg. background-wrapper or 2-Columns) throws an error, when showing in the backend. 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: Too few arguments to function T3SBS\T3sbootstrap\Backend\Preview\T3sbPreviewRenderer::__construct(), 0 passed in /typo3_src-11.5.14/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3208 and exactly 4 expected | ArgumentCountError thrown in file /typo3conf/ext/t3sbootstrap/Classes/Backend/Preview/T3sbPreviewRenderer.php in line 55. 

PHP 8, T3SB 5.2.3, T3 11.5.14, Container 2.0.4

**Comment by marinabey** [comment]
I can confirm this error with
- PHP 8
- TYPO3 11.5.16 (composer installation)
- t3sbootstrap 5.2.3
- container 1.6.1 (this version as a requirement of t3sbootstrap 5.2.3)

**Comment by t3solution** [comment]
I cannot reproduce this behavior.
I tried it with TYPO3 11.5.14 to 11.5.16 as well as PHP 8.0 and 8.1.
It works as expected!

**Comment by joergwiedemann** [comment]
What can i do? Downgrading T3SB or container?

**Comment by t3solution** [comment]
Can you set up access for me?

**Comment by hnadler** [comment]
DI works fine in 5.2.2 but is broken for me too in 5.2.3.

T3sbPreviewRenderer has B13\Container\Domain\Service\ContainerService as a dependency, but this class does not exist in b13/container:^1.6.0

Furthermore: what is the idea behind 

T3SBS\T3sbootstrap\Backend\Preview\T3sbPreviewRenderer:
    public: true
    
in Services.yaml (https://symfony.com/doc/4.3/service_container.html#public-versus-private-services)?

**Comment by t3solution** [comment]
hnadler is right! 
t3sbootstrap v5.2.3 depends on EXT:container v2.0.4
I will fix it with my next update!

Best practices to fix this issue in the meantime:
Uninstall and reinstall EXT:Container and EXT:t3sbootstrap with the current versions.

**Comment by marinabey** [comment]
With t3sbootstrap v5.2.3 and container v2.0.4 the same error (see first comment by joergwiedemann) is thrown as with t3sbootstrap v5.2.3 and container v1.6.1. 

With t3sbootstrap v5.2.2 and container v1.6.1 I don't get the error anymore, but I can't create content inside a container in the backend. 
I have set up a completely new and empty TYPO3 instance via Composer and can confirm this both on the customer project and on a completely fresh TYPO3 v11.5.16.

![container-backend](https://user-images.githubusercontent.com/24937949/191905621-770d8022-dc7f-4924-a15a-f578bc80b0c1.png)

**Comment by joergwiedemann** [comment]
Upgrade to T3SB 5.2.5 and Container 2.0.5 and everything is fine. Thank you, Helmut.

**Comment by joergwiedemann** [comment]
Reopend it for review for other users.

**Comment by asche76** [comment]
php 7.4 / 11.5.16 / 5.2.5 / container 2.0.5
-> creating elements inside column is  working
-> but drag&drop an CE from one into another column still not possible

![image](https://user-images.githubusercontent.com/47745128/192253519-dcfda114-40b8-4d0a-a480-a08646bef815.png)

**Comment by t3solution** [comment]
I can not understand this!
What other extensions do you have activated?

**Comment by asche76** [comment]
![image](https://user-images.githubusercontent.com/47745128/192269070-255cdaa6-436a-42c0-adba-f3f460cd62f8.png)

**Comment by joergwiedemann** [comment]
I cannot confirm this behavior on my systems, PHP 8.0 ,T3SB 5.2.5 everything fine. Also draggging CE into another CE ..

**Comment by marinabey** [comment]
The new version works for me as expected. Thanks for fixing this issue.

**Comment by asche76** [comment]
thx you guys, i will try this on fresh installation soon.

**Comment by asche76** [comment]
another VM, another system, same problem - no dragging possible.

**Comment by asche76** [comment]
ok have the guilty - the error occurs when tehe ext "paste_reference" ist installed.

**Comment by asche76** [comment]
paste_reference 2.0.1 now seems to work fine with T3SB.
